### PR TITLE
presence of 0xEE byte is a strong enough condition

### PR DESCRIPTION
**Pull request by pirroman**
I've got a case where the current check gives the wrong result.

### CODE REVIEW

**Comment by FauxFaux** [comment]
The spec is very specific that this is required, unless I'm reading it wrong.
Are you just under, or significantly under? Could you share the first 32kB of the device?

> A minimum of 16,384 bytes of space must be reserved for the GPT Partition Entry Array. If the block size is 512, the First Usable LBA must be greater than or equal to 34 (allowing 1 block for the Protective MBR, 1 block for the Partition Table Header, and 32 blocks for the GPT Partition Entry Array);

The place this library was being used was *very* sensitive to false positives; if you feed in a few hundred files full of noise (like a zip file or an mp3 file), it's job was to not accept those as a partition. I realise that most people feed in things they know are disk images, however.

**Comment by pirroman** [comment]
[gpt_data.zip](https://github.com/FauxFaux/bootsector/files/4636773/gpt_data.zip)
Yes, I can. I can tell you that where the size comes from, there are zeroes. Flag 0xee indicates EFI GPT and the other fields are essentially meaningless. I don't understand how frequent false positives can occur when "EFI PART" signature is checked further in the code.

**Comment by FauxFaux** [comment]
Okay, interesting. The length is zero, which is probably supposed to be defaulted to some value by some standard somewhere.

As you say, the validation of EFI PART is pretty good, although will give a weird error. Or blow the memory. I will fix that independently, though, I think.

**Comment by FauxFaux** [comment]
@pirroman: Can I use your example in a test case, committed to the repo?

**Comment by pirroman** [comment]
[gpt_data.zip](https://github.com/FauxFaux/bootsector/files/4638425/gpt_data.zip)
for committed to the repo better use this example. Thank you!
I can help with the processing of false positive cases. Or I could make a more suitable mistake. If you don't mind, of course.

**Pull request merged**
